repos:
- repo: https://github.com/mattlqx/pre-commit-ruby
  rev: v1.3.5
  hooks:
  - id: rubocop
- repo: local
  hooks:
  - id: validate
    name: Validate data files
    files: data/raw_data
    types_or: [ csv, yaml ]
    entry: "bundle exec rake data:validate"
    pass_filenames: false
    language: system

  - id: regenerate
    name: Regenerate DB/files
    files: data/raw_data
    types_or: [ csv, yaml ]
    entry: "bundle exec rake regenerate"
    pass_filenames: false
    language: system
